### ISSUE TITLE
Código em inglês e documentação em português

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/analises#12]
Essa _issue_ foi iniciada com o objetivo de discutir uma linguagem para o projeto. Para facilitar a padronização e leitura do código, vamos deixar o código em inglês e comentários, documentações e outras coisas que não são o código em si em português.

Para fechar essa _issue_ precisamos atualizar o código que já existe para o inglês e deixar o projeto de análises como os demais nessa organização.

**Comment by guilhermelowa** [comment]
Abri uma [Issue no Querido Diário](https://github.com/okfn-brasil/querido-diario/issues/215) sobre isso. Embora seja diferente, acho que muito do que eu falei lá se aplica aqui tb.

O inglês abre a possibilidade de colaboração internacional e estimula o aprendizado de algum vocabulário. O português é mais democrático, a maior parte dos contribuidores (se não todos) vão ser brasileiros e pra quem tem dificuldade com inglês, o código inglês pode ser desencorajador na hora de contribuir.

Tô fazendo meus notebooks agora o mais didático possível. Minha ideia é depois usar eles pra ensinar e deixar o mais fácil possível pra quem tá aprendendo dar uma olhada e aprender um pouco de data mining. Aprender foi um dos principais motivos pra contribuir com o projeto na pesquisa que a gente fez, então acredito que o material do próprio projeto se beneficiaria muito da contraparte: ensinar. Pra isso, acho que português é melhor. 

Algumas coisas ficam estranhas em português, é verdade. Por exemplo List Comprehensions. Mas nada impede de usar inglês nesses casos. Eu discordo da ideia de que aumenta muito o custo cognitivo em ter duas linguas. Pode até ser, se vocÊ tiver um parágrafo em cada língua, mas termos isolados em inglês não atrapalham. Vide os termos que eu usei em cima (data mining e List Comprehensions) e imagino que foram lidos naturalmente por quem sabe o que significa. A gente faz isso o tempo todo no dia-a-dia: typos, issue, pull request... por aí vai.

Então prefiro o código em português, ao menos pras análises. Facilita a compreensão, diminui o custo cognitivo de ler os notebooks (não precisa se preocupar com aprender inglẽs E análises, só com analises), é mais inclusivo. Acho que se a ideia de quem participa é aprender, português é a escolha mais lógica.

**Comment by anapaulagomes** [comment]
Bom, para um projeto local eu acredito que faz todo sentido ter a documentação e a comunicação (PRs, issues etc) em português. Mas o código, que já é boa parte em inglês por conta das linguagens de programação e todas as ferramentas que utilizamos, eu prefiro que esteja em inglês. Para poder programar a gente acaba precisando usar o inglês técnico ao menos. Chega um momento que fica difícil de ler duas linguagens ao mesmo tempo e misturar termos que já são consagrados para o português.

Uma boa documentação deve ser o suficiente para as pessoas aprenderem. Além disso, o Maria Quitéria e o Leis Municipais já estão seguindo esse padrão e, apesar dos desafios de traduzir coisas como _Tribunal de Contas dos Municípios_, parece funcionar bem - com comentários em português e o código todo em inglês. É uma boa prática ter um padrão entre os repositórios também.

**Comment by guilhermelowa** [comment]
> comentários em português e o código todo em inglês.

Eu gosto da ideia de comentários em português pra explicar alguma coisa mais rebuscada do inglês, tipo a tradução de TCM. Mas também já li o argumento de que isso atrapalha - inclusive na Issue do Querido Diário. Não acho que atrapalha, mas também não acho que atrapalha alguns termos em português (como disse aí acima), então não sou bom parâmetro. E nem tenho muita experiência pra falar.

>  É uma boa prática ter um padrão entre os repositórios também.

É, já existir esse padrão em inglês no projeto acho que conta muito.

> Para poder programar a gente acaba precisando usar o inglês técnico ao menos.

É uma boa pergunta. Não sei. Conheço muita gente que usa os comandos do UNIX sem saber que _cd_ é Change Directory, _pwd_ é Print Working Directory etc. São nomes dessassociados de semântica. E quando eu mostro isso as pessoas acham bem mais fácil usar o comando. Meu palpite é que acontece a mesma coisa com o código em inglês: _for_ é só um termo que faz o código repetir. Mas eu realmente não sei pq não foi minha experiência - quando comecei a programar eu já sabia inglẽs.

Fiquei curioso. Acho que vou rodar um formulário sobre isso com os colegas da UEFS.

**Comment by anapaulagomes** [comment]
Bom, visto que houve tempo pra outras pessoas se manifestarem e algo precisa ser decidido, vou usar meu papel de [ditadora benevolente](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) do momento para decidir que ficamos com código em inglês e comentários em português. Vou deixar essa _issue_ aberta para lembrar de fazermos a atualização do que já existe.

**Comment by guilhermelowa** [comment]
Hahahahaha eu concordo com a decisão! Embora discorde do que foi decidido.

Sonhei com isso hoje. Minha dúvida no sonho era: e os notebooks? Que tem trechos de código seguidos de markdown. O markdown é texto, quase uma documentação. Faz sentido ser em português, certo? E aí o código em inglês. Mas aí nesse caso não fica alternando inglês / português do mesmo jeito? Não dificulta igual?

E o nome dos arquivos? Em português ou inglês? Hoje temos quase todos os arquivos em inglês, menos os notebooks.

**Comment by anapaulagomes** [comment]
O texto em markdown nada mais é do que documentação. Os nomes de arquivo seguem a mesma lógica que o código (em inglês). Para facilitar, podemos criar no README um índice de notebooks, por exemplo.
