### ISSUE TITLE
Análise do auxílio emergencial recebido por servidores municipais

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/analises#14]
Há alguns dias atrás o Ministério da Cidadania juntamente com a CGU liberou a base de dados dos beneficiários do auxílio emergencial nos meses de Abril e Maio. Fizemos o filtro desses dados pela cidade de Feira de Santana. Ambas bases podem ser encontradas [aqui](https://www.kaggle.com/dadosabertosdefeira/beneficirios-do-auxlio-emergencial).

O Tribunal de Contas do Município publica os contracheques dos funcionários público da cidade por órgão (prefeitura, câmara etc). Precisamos acessar a página de [Pessoal](https://www.tcm.ba.gov.br/portal-da-cidadania/pessoal/), e baixar todos os contracheques de Abril e Maio para cada órgão. É possível baixar um arquivo `.XLS` com as informações. O ideal é abrir esse arquivo, limpar os dados desnecessários (apenas coisas como calendário, mantendo os registros originais) e publicar os `.csv` para que a análise seja reproduzível.

Para fazer:
- [x] Fazer o _download_ de todos os contracheques nos meses de Abril e Maio
- [x] Converter esses arquivos para `.csv`. Se possível, mergeá-los em um só (adicionando o órgão e o mês e ano).
- [ ] Fazer o _match_ das bases do auxílio emergencial com os salários
- [ ] Fazer uma análise exploratória (contar quantos nomes foram encontrados, quanto seria economizado caso esses casos sejam confirmado e quanto seria devolvido aos cofres públicos etc)

Desafios:
- [ ] Homônios são fáceis de serem encontrados e os dados do TCM-BA não tem o CPF para nos ajudar a reduzir as chances de acusar injustamente. Podemos tentar fazer um pedido de informação ao TCM-BA dos CPFs dos servidores (parcial, anonimizado como a base do auxílio emergencial) para auxílio na análise.
- [ ] Temos que verificar os limites da exposição de nomes de pessoas. Talvez manter o primeiro nome e abreviar os sobrenomes? Seria bom checar os limites legais disso, para evitar problemas com acusações injustas.

**Comment by vihvs** [comment]
> Para fazer:
> 
>     * [X]  Fazer o _download_ de todos os contracheques nos meses de Abril e Maio

Algumas buscas retornaram o erro `Os dados não foram informados pelo Jurisdicionado!`

Foram as seguintes buscas:

Abril
- Consórcio Público Interfederativo de Saúde da Região de Feira de Santana 

Maio
- Instituto de Previdência de Feira de Santana
- Fundação Hospitalar de Feira de Santana
- Superintendência Municipal de Trânsito
- Fundação Cultural Municipal Egberto Tavares Costa
- Superintendância Municipal de Proteção e Defesa do Consumidor
- Agência Reguladora de Feira de Santana
- Consórcio Público Interfederativo de Saúde da Região de Feira de Santana

**Comment by vihvs** [comment]
O match dos nomes dos servidores e das pessoas que receberam auxílio emergencial em Feira de Santana foi feito. 
Como foi realizado pelo nome e a quantidade de homônimos é grande, filtrei os nomes de servidores que potencialmente podem ter recebido o auxílio e que receberam acima de 4 mil reais de salário total em Abril ou Maio. Essa lista de nomes será compartilhada com @anapaulagomes e a imprensa para pedir ao TCM-BA os CPFs desses servidores e, assim, poderei comparar se o CPF está entre os que receberam o auxílio emergencial.
O código não será publicado pois contém dados pessoais de diversas pessoas e precisamos estudar cisso pode ser público sem causar danos legais.

**Comment by anapaulagomes** [comment]
Infelizmente não conseguimos os CPFs dos servidores para fazer o _match_ adequado. Solicitamos ao TCM-BA, que nos indicou entrar em contato com a Receita Federal, que disse não poder disponibilizar tal informação.
