### ISSUE TITLE
Adicionar parsers para campos relacionados a natureza das despesas

### ISSUE THREAD

**Issue by guilhermelowa** [DadosAbertosDeFeira/analises#42]
O dataset de pagamentos da Prefeitura vem com os seguintes campos: credor, valor, bem_ou_servico_prestado, natureza, acao, funcao, subfuncao, processo_licitatorio, fonte_recurso. Alguns destes campos contém typos e entradas não formatadas.

Por exemplo, em processo_licitatorio, temos os seguintes valores (em str):
ISENTO, ENTO, Isento, SENTO, sento. Todos se referem ao valor mesmo valor: isento.

Existe um parser para "valor" em scripts/parsers.py e um pra "processo_licitatorio" feito no PR #25 . No entanto, os campos natureza, funcao e subfuncao também contém os mesmos erros e não há parsers pra estes. Também cabe conferir se mais algum campo precisa de um parser semelhante.

**Comment by anapaulagomes** [comment]
Os campos natureza, funcao e subfuncao não precisam de parsers porque pegamos os dados já corretos e normalizados a partir do código da natureza da despesa, direto dos dados do TCM-BA. Mais informações sobre isso aqui: https://github.com/DadosAbertosDeFeira/analises/wiki/Dados#classifica%C3%A7%C3%A3o-or%C3%A7ament%C3%A1ria.
Já havia escrito código para fazer isso... Os métodos utilitários deveriam estar em scripts (ou em um dos notebooks). Vou verificar o que houve e adicioná-los novamente por lá. 🤔

**Comment by guilhermelowa** [comment]
Verdade, Ana! Não lembrava desse código que você já tinha feito e não relacionei ele com função e subfunção. Mas é isso aí, então. É pra colocar esse código nos parsers, então? De fazer um join com o DataFrame da natureza das despesas?
