### ISSUE TITLE
Criar modelo para identificar localizações em texto

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/analises#46]
Temos fontes de dados como licitações e diários oficiais que contém informações relevantes a respeito de ruas, bairros e outras localizações. Porém essas informações não estão estruturadas. Nosso desafio é identificar localizações, tornando possível a busca a partir do frontend e facilitando análises desses dados.

A partir do modelo desenvolvido aqui poderemos indexar os dados que temos a partir de localizações na [Maria Quitéria](https://github.com/DadosAbertosDeFeira/maria-quiteria/issues/131).

**Comment by guilhermelowa** [comment]
Não entendi, Ana. Seria indexar os documentos pela localização? Ou indexar de forma a conseguir buscar pela localidade? Se for o último, já é possível indexando por TF-IDF, feito no notebook buscador, no PR #27 . Mas lá os textos (leis e atas) estão em CSV. Não sei como seria pra colocar isso online.

**Comment by anapaulagomes** [comment]
Não, indexar é uma etapa depois que o modelo está pronto e vai ser feito na Maria Quitéria.
Eu entendo que o #27 é sobre semelhança de leis. Também identifica localizações? Como o PR ainda não está pronto, não foi revisado por completo ainda e a descrição não fala nada sobre localidades.

**Comment by guilhermelowa** [comment]
Não identifica localizações, _per se_, mas se você buscar uma localização retorna os documentos relevantes pra ela. Tá no caderno buscador_leis.ipynb, que deveria estar em outro PR. Não tá documentado aqui, mas tinha comentado contigo que o buscador acha os documentos relevantes pra nomes de localizações e pessoas. Com TF-IDF já resolve isso

**Comment by anapaulagomes** [comment]
Mas, de todo jeito, precisamos de um notebook com uma análise dos resultados - nem que seja usando o que tu já desenvolveu (e que não vai estar no #27 porque é sobre leis...).

**Comment by anapaulagomes** [comment]
Sendo feito no Tomba: https://github.com/DadosAbertosDeFeira/tomba/.
