### ISSUE TITLE
Incluir materiais de estudo no CONTRIBUTING.md

### ISSUE THREAD

**Issue by guilhermelowa** [DadosAbertosDeFeira/analises#55]
Incluir os [materiais de estudo](https://github.com/DadosAbertosDeFeira/analises/wiki/Materiais-para-estudo) no CONTRIBUTING.md, na seção Antes de começar.

**Comment by guilhermelowa** [comment]
Vou fazer essa!

**Comment by guilhermelowa** [comment]
Posso ficar com essa tarefa!

**Comment by anapaulagomes** [comment]
Ué, a gente não combinou de deixar na issue os materiais e ir atualizando o wiki? Acho q no contributing pode ficar grande demais e fora de propósito. A pessoa não precisa acessar os materiais para vontribuir. Não acho q seja o melhor lugar.

**Comment by guilhermelowa** [comment]
Fechada por #54 . Desculpem, esqueci de incluir lá pq dos problemas etc
