### ISSUE TITLE
Modificar hook de arquivos grandes demais

### ISSUE THREAD

**Issue by guilhermelowa** [DadosAbertosDeFeira/analises#60]
Acabei de tentar commitar um notebook pequeno, sem output das células, e recebi o seguinte aviso:

`analysis/expenses_exploratory_analysis.ipynb (2892 KB) exceeds 500 KB.`

Mesmo tentando ampliar o tamanho limite pra este commit, como descrito [aqui](https://gist.github.com/guysmoilov/ddb3329e31b001c1e990e08394a08dc4), não consegui commitar. Mesmo erro. Minha solução foi rodar com `git commit --no-verify`, já que todos os outros testes estavam passando.

Se notebooks tão pequenos já passam do limite de tamanho, minha sugestão é aumentar o limite do tamanho. A própria página citada aí em cima sugere que o limite padrão é 5 MB, mas estamos com 500 KB por algum motivo.

**Comment by anapaulagomes** [comment]
@guilhermelowa, o que tinha no seu notebook pra ter quase 3MB? Olhei os outros notebooks que temos e nenhum passa de 1MB.

**Comment by guilhermelowa** [comment]
Agora foi o HTML gerado pelo script que deu 613KB

**Comment by anapaulagomes** [comment]
A [documentação oficial](https://github.com/pre-commit/pre-commit-hooks#check-added-large-files) diz que o padrão é 500kb. Podemos aumentar para 2 MB e ver como fica.
