### ISSUE TITLE
Criar um notebook base para análise de dados do TSE

### ISSUE THREAD

**Issue by anapaulagomes** [DadosAbertosDeFeira/analises#62]
Esse "notebook-template" deve possibilitar qualquer pessoa a fazer análises dos dados de candidaturas do TSE, incluindo instruções de como baixar os dados, limpá-los e visualizá-los.

Importante:

* Incluir como filtrar por cidade (no nosso caso, Feira de Santana)
* Fonte de dados: https://www.tse.jus.br/eleicoes/estatisticas/repositorio-de-dados-eleitorais-1/repositorio-de-dados-eleitorais

**Comment by vihvs** [comment]
@anapaulagomes você consegue editar essa issue como 'on progress' por favor?
Já criei um branch com as mudanças em [vihvs/analises/62-template_tse](https://github.com/vihvs/analises/tree/62-template_tse )

**Comment by guilhermelowa** [comment]
@vihvs você pode abrir um draft PR? 

A gente discutiu na Issue #12 que o código seria em inglês e a documentação em português. Se quiser posso mudar isso pra você

**Comment by vihvs** [comment]
Esse notebook é inspirado nos notebooks dos projetos guiados do Datacamp, para ajudar pessoas iniciantes a começar a fazer análise de dados e lidar com problemas iniciais que esse arquivo gera.
Ainda não fiz pull request porque ainda irei fazer revisão e organizar em passos como os notebooks guiados.

<img width="1596" alt="Screenshot 2020-10-30 at 15 22 26" src="https://user-images.githubusercontent.com/7208924/97732702-371efa80-1ad7-11eb-9178-b96e82f6267c.png">

**Comment by anapaulagomes** [comment]
Feito em #66.
