### ISSUE TITLE
Excluir verificação do tamanho da linha do diretório analysis

### ISSUE THREAD

**Issue by guilhermelowa** [DadosAbertosDeFeira/analises#68]
### Problema
Frequentemente inserimos URL no markdown dos notebooks, utilizando a notação [nome](URL). Ao converter este notebook para script Python, o flake8 indica que a linha é muito grande e não permite finalizar o commit, como aconteceu no PR #24 onde se iniciou esta discussão.

### Propostas de solução
- Excluir esta restrição da pasta `analysis`, como indicado aqui: https://flake8.pycqa.org/en/latest/user/configuration.html

**Comment by anapaulagomes** [comment]
Talvez seja melhor colocar pra excluir de notebooks apenas (`*.ipynb`) porque agora temos a pasta `templates` também.
